[project]
name = "mcp-server-stub-python"
version = "0.1.0"
description = "This is an MCP Server stub implementation that can be extended for tool/agent integration"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.1",
]
